sudo: required

dist: trusty

language: node_js

node_js:
  - "8"

env:
  global:
    - secure: "Eq0t3zP1PeIHrb/c4XRLyLiErc/du95iwdGyHyElx6Yi9ssdyJEzyf43Zss2lUFjr4ExUYJoiNmf6tcQq/9w0Qcod5yHIfM+okqdGKCEkdi9C5wzTsNc03csZQcptdQou37cLnYH2kYmOH0LMcnO6JK1LEP/IXvGbleohE8TxqSiQmIJhNLFRknqpriint4Ic70wpAVlEiMDY0r3bGfmmvPUrj1c1oerJUmS/idykF/STempGFpbvOpONo87qn3lsJuw/dG/l1JzEoGj3R5/jUtTZoCQkW4WwEQgcjI776pZSrz7xB9+Onl5OiRh2Fb7IVema23bN9ky7KUCGzqG5ZV+izE6v3+J96o7viB4xib2HJlBAFUB2/gqeNyHl6DoqUGlK/gBSy7BJljoN691da6L3BwWor55p6/WREgB6GKbhX3PiqgHmoi8Qrc45jQpdMha+b94Fm0VgLWXljFdA5ft8NSom5v8QJTLjlXf+Lq4ES6U1ifwogO9uv1pkZFcmF8SgMEEB5DnVKmRDkEGfMHjzw0F1QYNRVO5zhny81jREeqXizsWG5y2TBOymGKF6MtS4izaT+7bW8XngI2+x/7HyGvV/cHploOUgkQ6DrTtglzrApygzGPMHTJuRSBcSNZHvgb5G6fL5BGi+jb3L+2yKCniiwxowTC894zOMY4="
    - GIT_DEPLOY_DIR=public # this is the default output dir of Hugo
    - GIT_DEPLOY_BRANCH=master # this is the target branch, replace by gh-pages for Project Pages
    - GIT_DEPLOY_USERNAME="Travis CI" # dummy name
    - GIT_DEPLOY_EMAIL=andreas.sander@hotmail.de # replace by your email

branches:
  only:
    - master # allow build on master
    - develop # allow build on develop

before_install:
  - sudo apt-get -y install golang # install go
  - sudo apt-get -y install python3 # install python 3
  - sudo apt-get -y install python3-pip # install python 3 pip module

install:
  - rm -rf public || exit 0 # cleanup previous run
  - npm install
  - go get -u -v github.com/spf13/hugo # download hugo
  - python3 -m pip install --user Pygments

script:
  - ./node_modules/.bin/gulp --production # run gulp task in production mode
  - hugo # generate static files

after_success:
  - bash deploy.sh # run the deploy script
