baseurl = "https://andi1984.de/"
languageCode = "en-us"
title = "\"A general webdeveloper's blog...\""
theme = "andi"
relativeURLs = "true"
pygmentsCodeFences = "true"
pygmentsStyle = "vs"
[taxonomies]
tag = "tags"
series = "series"
language = "languages"
