baseurl = "https://andi1984.github.io/"
languageCode = "en-us"
title = "\"A general webdeveloper's blog...\""
theme = "andi"
relativeURLs = "true"
pygmentsuseclasses = "true"
PygmentsCodeFences = "true"
