[build]
  publish = "public"
  command = "npm run deploy"

[context.production.environment]
  HUGO_VERSION = "0.50"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.55"
